export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INGREDIENT_FETCHED_FAILED = 'INGREDIENT_FETCHED_FAILED';

export const PURCHASE_INIT ="PURCHASE_INIT";
export const ORDER_START = "ORDER_START";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";

export const ORDERS_FETCH_INIT = "ORDERS_FETCH_INIT";
export const ORDERS_FETCH_SUCCESS = "ORDERS_FETCH_SUCCESS";
export const ORDERS_FETCH_FAILURE = "ORDERS_FETCH_FAILURE";


export const LOGIN_INIT = "LOGIN__INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const REDIRECT_URL_CREATED = "REDIRECT_URL_CREATED";





